import { LUCIDE_ICON_NAME_LIST } from "./lucideIconNames";

/** Every Lucide icon name in kebab-case. The list is generated by `pnpm gen:icons`. */
export const LUCIDE_ICON_NAMES: ReadonlySet<string> = new Set(LUCIDE_ICON_NAME_LIST);
