// Writes src/validate/lucideIconNames.ts from the installed lucide-react.
// Run `pnpm gen:icons` after upgrading lucide-react, then commit the result.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import dynamicIconImports from "lucide-react/dynamicIconImports.mjs";

const require = createRequire(import.meta.url);
const lucidePackage = require.resolve("lucide-react/package.json");
const { version } = JSON.parse(readFileSync(lucidePackage, "utf8"));

const names = Object.keys(dynamicIconImports).sort();
const body = names.map((name) => `  "${name}",`).join("\n");
const out = `// Generated by scripts/gen-icons.mjs from lucide-react ${version}. Do not edit by hand.
// Run \`pnpm gen:icons\` after upgrading lucide-react.
export const LUCIDE_VERSION = "${version}";

export const LUCIDE_ICON_NAME_LIST: readonly string[] = [
${body}
];
`;
writeFileSync(fileURLToPath(new URL("../src/validate/lucideIconNames.ts", import.meta.url)), out);
console.log(`Wrote ${names.length} icon names from lucide-react ${version}`);
