// Generates the icon set files from scripts/icon-set.mjs:
//   src/icons/iconNames.ts  the allowed names (used by the validator, no React)
//   src/icons/iconMap.ts    name -> Lucide component (used by the renderer, one static chunk)
//   docs/guide.md           the list between the icons:start and icons:end markers
// Run `pnpm gen:icons` after editing the set or upgrading lucide-react, then commit the result.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import * as lucide from "lucide-react";
import { ICON_GROUPS } from "./icon-set.mjs";

const here = (path) => fileURLToPath(new URL(path, import.meta.url));
const pascal = (name) =>
  name
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

const names = Object.values(ICON_GROUPS).flat();
const duplicates = names.filter((name, i) => names.indexOf(name) !== i);
if (duplicates.length) throw new Error(`Duplicate icons in icon-set.mjs: ${duplicates.join(", ")}`);

const missing = names.filter((name) => !(pascal(name) in lucide));
if (missing.length) throw new Error(`Not exported by lucide-react: ${missing.join(", ")}`);

const sorted = [...names].sort();
const header =
  "// Generated by scripts/gen-icons.mjs from scripts/icon-set.mjs. Do not edit by hand.\n";

writeFileSync(
  here("../src/icons/iconNames.ts"),
  `${header}// Run \`pnpm gen:icons\` after changing the icon set.\nexport const ICON_NAMES = [\n${sorted.map((n) => `  "${n}",`).join("\n")}\n] as const;\n\nexport type IconName = (typeof ICON_NAMES)[number];\n`,
);

writeFileSync(
  here("../src/icons/iconMap.ts"),
  `${header}import type { LucideIcon } from "lucide-react";\nimport {\n${sorted.map((n) => `  ${pascal(n)},`).join("\n")}\n} from "lucide-react";\nimport type { IconName } from "./iconNames";\n\nexport const ICON_MAP: Record<IconName, LucideIcon> = {\n${sorted.map((n) => `  "${n}": ${pascal(n)},`).join("\n")}\n};\n`,
);

const guidePath = here("../../../docs/guide.md");
const guide = readFileSync(guidePath, "utf8");
const list = Object.entries(ICON_GROUPS)
  .map(([group, icons]) => `- **${group}:** ${icons.map((n) => `\`${n}\``).join(", ")}`)
  .join("\n");
const start = "<!-- icons:start (generated by pnpm gen:icons, do not edit by hand) -->";
const end = "<!-- icons:end -->";
const pattern = /<!-- icons:start[^>]*-->[\s\S]*?<!-- icons:end -->/;
if (!pattern.test(guide)) throw new Error("docs/guide.md has no icons:start / icons:end markers");
writeFileSync(guidePath, guide.replace(pattern, `${start}\n${list}\n${end}`));

console.log(`Wrote ${names.length} icons`);
